language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - pypy3

cache:
    pip: true
    directories:
        - $HOME/eyeD3-test-data

install:
    - pip install tox-travis
    - pip install coveralls
    - pip install -U -r requirements.txt
    - pip install -U -r requirements/test.txt
    - pip install -e .
    - make TEST_DATA_DIR=$HOME test-data

# command to run tests
script: tox

after_success:
  - coveralls
