name: Main eyeD3 workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ Ubuntu, MacOS, Windows ]
        python-version: [ "3.9", "3.8", "3.7", "3.6"]

    steps:
    - uses: actions/checkout@v2

    # Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Test data
    - name: Test data cache
      id: cache-test-data
      uses: actions/cache@v2
      with:
        path: ~/eyeD3-test-data
        key: ${{ runner.os }}-test-data

    - name: Install test data
      # If the directory exists it is not re-downloaded, but symlinks are
      # restored, and that's needed after a cache is restored.
      run: make TEST_DATA_DIR=~ test-data

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test] .[display-plugin]

    # Run tests
    - name: Tests
      run: |
        make lint
        make test
        make check-manifest

    # XXX: What to do with coverage? Was using coverall, meh. Github pages?
    # XXX: Removed pypy3 because of some coverage module not found error...
